spring.application.name=servicio-analiticas
server.port=8083
spring.datasource.url=jdbc:mysql://localhost:3306/demo_db_analitica?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
app.jwt.secret=7j4b8AzkK75FF4MXLG0wVRbehPlE3o0KuDbUDIbXwDI=
app.jwt.expiration-minutes=60
